### ISSUE TITLE
problem about hypothesis test in cnv analysis based TCGA

### ISSUE THREAD

**Issue by xuexingwangzhedishitian** [huerqiang/GeoTcgaData#1]
I notice that there are two functions **diff_CNV** and **differential_cnv** for different analysis based on CNV. One uses **fisher test**, the other uses **chi quare test**. And the selection of threshold for counting before hopothesis test is also different. The function of differential_cnv choose **0.5** for numeric copy number values. I want to know that why you choose **0.5** for this function and the difference between  two functions **diff_CNV** and **differential_cnv**.
  I am glad for you reply.

**Comment by huerqiang** [comment]
1. `differential_cnv` was written a long time ago, and `diff_CNV` is an improved version. I recommend `diff_CNV` as the standard process in the documentation of the package. The results of both functions are reasonable. 
2. The reason why differential_cnv uses 0.5 as the threshold is based on such grouping: 
Less than 0.5: homozygous loss. 
-0.5 to 1.5: hemizygotic deletion. 
**1.5 to 2.5: normal copy number .** 
2.5 to 3.5: Copy number amplification 
More than 3.5: high-level amplification. 
3. `diff_CNV` directly processes the Gene Level Copy Number Scores files obtained by TCGA, and its grouping method is as follows https://docs.gdc.cancer.gov/Data/Bioinformatics_Pipelines/CNV_Pipeline/. 
4. The fisher exact test is more accurate than the chi-square test, so I use it in the new function.

**Comment by xuexingwangzhedishitian** [comment]
thank you for your reply.
  I have been read the CNV analysis workflown(https://docs.gdc.cancer.gov/Data/Bioinformatics_Pipelines/CNV_Pipeline/).  
I still have some problems.  
  The genotype files with continuous copy number values are generated by GITSIC. Based on the cutoff of 0.3, copy number values could be transfered into -1,0 and 1. Processed file is  named the Gene Level Copy Number Scores files. I want to know the funciton of differential_cnv is applicable for the output genotype files with continuous copy number values generated by GITSIC.
I am glad for you reply.

**Comment by huerqiang** [comment]
It is not suitable for continuous data and needs to be converted to discrete data.

**Comment by xuexingwangzhedishitian** [comment]
I mean wether the 0.5 cutoff of the function of `differential_cnv` is applicable to the output focal-level files that generated by GITSIC as follows.
Gene Symbol	Gene ID	Cytoband	TCGA-27-2519-01A-01D-0784-01	TCGA-06-5408-01A-01D-1694-01
ACAP3	116983	1p36.33	0.000	-0.873
ACTRT2	140625	1p36.32	0.000	-0.873
.....
Thank you for your reply again.

**Comment by huerqiang** [comment]
I suggest that the threshold value should be 0.3 recommended by TCGA official website now.

**Comment by xuexingwangzhedishitian** [comment]
Thanks for your reply. I get it.
